## library() calls go here
library(dotenv)
library(drake)
library(ggplot2)
library(ICIKendallTau)
library(visualizationQualityControl)
library(dplyr)
library(rmarkdown)
library(tidyr)
library(knitrProgressBar)
library(furrr)
library(rlang)
library(patchwork)
future::plan(multicore)

theme_set(cowplot::theme_cowplot())
