---
title: 'Supplemental Table 1'
output: 
  rmarkdown::word_document:
    reference_docx: 'table_template.docx'
    keep_md: true
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, 
                      message = FALSE, fig.width = 8, 
                      fig.height = 6, fig.keep = "all",
                      fig.process = dn_modify_path,
                      tab.cap.style = "paragraph",
                      tab.cap.pre = "",
                      tab.cap.sep = "",
                      dpi = 600,
                      dev.args = list(png = list(type = "cairo")))
```

`r supp_table_count$label_text("yeast_outliers")`.
Yeast dataset median correlation values and outlier determination for each outlier from each of the correlation methods.
Abbreviations for different measures and data are: IK: ICI-Kt; IKC: ICI-Kt * Completeness; M: Manuscript; PL1: Pearson Log(x + 1); PN0: Pearson No Zeros.

```{r yeast_table2}
#yeast_ft_out = set_caption(yeast_table,
  # caption = paste0(paste_label("Table S", supp_table_count, "yeast_outliers"), ". Yeast dataset median correlation values and outlier determination for each outlier from each of the correlation methods."), style = "paragraph")
yeast_ft_out = yeast_table %>%
  set_nice_widths() %>%
  put_outlier_right()
yeast_ft_out
```
